// This file was auto-generated by ML.NET Model Builder. 

using System;
using Hamburger_MenuML.Model;

namespace Hamburger_MenuML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Sexo = @"FEMENINO",
                Edad = 36F,
                Esta_emabarazada = @"NO",
                Fecha_ingreso = @"24/06/2020",
                Fecha_inicio_sintomas = @"24/06/2020",
                Fiebre = @"NO",
                Tos = @"NO",
                Diarrea = @"NO",
                Vomito = @"SI",
                Diabetes = @"NO",
                Epoc = @"NO",
                Asma = @"NO",
                Hipertension = @"NO",
                Obesidad = @"NO",
                Tabaquismo = @"SI",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Diagnostico_probable with predicted Diagnostico_probable from sample data...\n\n");
            Console.WriteLine($"Sexo: {sampleData.Sexo}");
            Console.WriteLine($"Edad: {sampleData.Edad}");
            Console.WriteLine($"Esta_emabarazada: {sampleData.Esta_emabarazada}");
            Console.WriteLine($"Fecha_ingreso: {sampleData.Fecha_ingreso}");
            Console.WriteLine($"Fecha_inicio_sintomas: {sampleData.Fecha_inicio_sintomas}");
            Console.WriteLine($"Fiebre: {sampleData.Fiebre}");
            Console.WriteLine($"Tos: {sampleData.Tos}");
            Console.WriteLine($"Diarrea: {sampleData.Diarrea}");
            Console.WriteLine($"Vomito: {sampleData.Vomito}");
            Console.WriteLine($"Diabetes: {sampleData.Diabetes}");
            Console.WriteLine($"Epoc: {sampleData.Epoc}");
            Console.WriteLine($"Asma: {sampleData.Asma}");
            Console.WriteLine($"Hipertension: {sampleData.Hipertension}");
            Console.WriteLine($"Obesidad: {sampleData.Obesidad}");
            Console.WriteLine($"Tabaquismo: {sampleData.Tabaquismo}");
            Console.WriteLine($"\n\nPredicted Diagnostico_probable: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
