// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Hamburger_MenuML.Model
{
    public class ModelInput
    {
        [ColumnName("sexo"), LoadColumn(0)]
        public string Sexo { get; set; }


        [ColumnName("edad"), LoadColumn(1)]
        public float Edad { get; set; }


        [ColumnName("esta_emabarazada"), LoadColumn(2)]
        public string Esta_emabarazada { get; set; }


        [ColumnName("fecha_ingreso"), LoadColumn(3)]
        public string Fecha_ingreso { get; set; }


        [ColumnName("fecha_inicio_sintomas"), LoadColumn(4)]
        public string Fecha_inicio_sintomas { get; set; }


        [ColumnName("diagnostico_probable"), LoadColumn(5)]
        public float Diagnostico_probable { get; set; }


        [ColumnName("fiebre"), LoadColumn(6)]
        public string Fiebre { get; set; }


        [ColumnName("tos"), LoadColumn(7)]
        public string Tos { get; set; }


        [ColumnName("diarrea"), LoadColumn(8)]
        public string Diarrea { get; set; }


        [ColumnName("vomito"), LoadColumn(9)]
        public string Vomito { get; set; }


        [ColumnName("diabetes"), LoadColumn(10)]
        public string Diabetes { get; set; }


        [ColumnName("epoc"), LoadColumn(11)]
        public string Epoc { get; set; }


        [ColumnName("asma"), LoadColumn(12)]
        public string Asma { get; set; }


        [ColumnName("hipertension"), LoadColumn(13)]
        public string Hipertension { get; set; }


        [ColumnName("obesidad"), LoadColumn(14)]
        public string Obesidad { get; set; }


        [ColumnName("tabaquismo"), LoadColumn(15)]
        public string Tabaquismo { get; set; }


    }
}
